services:
  azuredns:
    container_name: azuredns
    hostname: azuredns
    restart: unless-stopped
    build: https://github.com/grahamcropley/AzureDnsAutoUpdater.git
    image: grahamcropley/azurednsautoupdater:latest
    networks:
      - containers
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - AZURE_CLIENTID=YOUR_CLIENT_APP_ID
      - AZURE_CLIENTSECRET=YOUR_CLIENT_APP_SECRET
      - AZURE_TENANTID=YOUR_AZURE_TENANT_ID
      - AZURE_RESOURCEGROUP=YOUR_AZURE_RESOURCE_GROUP
      - AZURE_CNAME=YOUR_CNAME_INCLUDING_DOMAIN_TLD

networks:
  containers:
    external:
      name: containers
